#!/bin/bash

USER=
PASS=
DOMAIN=

# Update Dynamic DNS Record
IP=$(curl http://ifconfig.me 2> /dev/null)
IP6=$(curl -6 https://ifconfig.co/ 2> /dev/null)

curl https://$USER:$PASS@domains.google.com/nic/update?hostname=$DOMAIN&myip=$IP
